/* Lawtrades SMB - hero and step animations. Generated by build.py.
   Vanilla JS, no dependencies. Element ids are Smb- prefixed. */
/* ---- how it works: one matter room ----

   Watch plays the story: your own messages are typed into the composer, theirs
   arrive behind a typing indicator, and the four steps follow along. Read drops
   the whole transcript in and lets you scroll it yourself. Both keep the link
   between the story and the rail, which is the point of the section. */
(function(){
  var rail=document.getElementById('Smb-mrail'), tin=document.getElementById('Smb-mtin'),
      thr=document.getElementById('Smb-mthread'),
      room=document.getElementById('Smb-mroom'),
      pin=document.getElementById('Smb-mpin');
  if(!rail || !tin || !thr) return;
  var reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  /* Drop these next to the hosted css and js and the faces appear. Until then
     every avatar falls back to its monogram, so nothing depends on them. */
  /* Avery's face is already embedded in this page and is applied in CSS, so it
     needs no file. Dana and Priya stay as monograms until real photos exist:
     one face beside two monograms reads as a half loaded list, which is worse
     than three monograms. */
  var PHOTO_BASE='';
  var PHOTO={};
  function shot(n){
    return PHOTO[n] ? '<img src="'+PHOTO_BASE+PHOTO[n]+'" alt="" onerror="this.remove()">' : '';
  }
  function ini(n){ return n.split(' ').map(function(w){ return w[0]; }).join('').slice(0,2); }

  var CANDS=[
    {n:'Avery R.', f:'Smb-f-av', m:'Commercial &middot; 9 years &middot; New York',
     why:'18 SaaS contracts, 6 at your deal size'},
    {n:'Dana M.',  f:'Smb-f-dm', m:'Commercial &middot; 6 years'},
    {n:'Priya S.', f:'Smb-f-ps', m:'IP and commercial &middot; 11 years'}
  ];
  function cands(){
    return '<div class="Smb-mcands">'+CANDS.map(function(c,i){
      return '<div class="Smb-mcand'+(i===0?' Smb-top':'')+'">'
       +'<span class="Smb-mcav '+c.f+'">'+(c.f?'':ini(c.n))+shot(c.n)
       +'</span><span style="flex:1"><b>'+c.n+'</b><em>'+c.m+'</em>'
       +(c.why?'<u>'+c.why+'</u>':'')+'</span>'
       +'<span class="Smb-mcsel">'+(i===0?'<i class="ph-bold ph-check"></i>':'')+'</span></div>';
    }).join('')+'</div>';
  }

  var T=[
   {s:0,w:'you',n:'You',t:'11:47 PM',b:
    '<p>Client sent a 40 page MSA, due tomorrow. Is this normal?</p>'
    +'<span class="Smb-mchip"><i class="ph ph-file-pdf"></i><b>Northstar_MSA_v4.pdf</b>'
    +'<s>40 pages</s></span>'},
   {s:0,w:'agent',n:'Agent',t:'11:47 PM',b:
    '<p>Rushed, but not unusual. How big is the deal?</p>'},
   {s:0,w:'you',n:'You',t:'11:48 PM',b:'<p>About $80k a year. First contract with them.</p>'},
   {s:0,w:'agent',n:'Agent',t:'11:49 PM',b:
    '<p>Worth a real review. Here is the brief I am matching against.</p>'
    +'<div class="Smb-mcl"><div class="Smb-mclh"><b>Matter brief</b><s>Prepared by Agent</s></div>'
    +'<div class="Smb-mclr">Contract<b>40 page MSA, SaaS</b></div>'
    +'<div class="Smb-mclr">Deal size<b>About $80k a year</b></div>'
    +'<div class="Smb-mclr">Deadline<b>Signature due tomorrow</b></div></div>'},
   {s:1,w:'agent',n:'Agent',t:'11:51 PM',b:'<p>Three have done this before.</p>'+cands()},
   {s:2,w:'agent',n:'Agent',t:'11:55 PM',cont:1,b:
    '<p>Terms first. Nothing starts until both of you sign.</p>'
    +'<div class="Smb-meng"><div class="Smb-mengh"><b>Engagement &middot; Contract review</b>'
    +'<em>$300 an hour. No retainer. Over 4 hours needs your approval.</em></div>'
    +'<div class="Smb-mengs"><div>You<b>Pending</b></div>'
    +'<div>Avery R.<b>Pending</b></div><div>Billed<b>Weekly</b></div></div></div>'},
   {s:2,w:'you',n:'You',t:'11:56 PM',b:'<p>Fair. Going with Avery.</p>'},
   {s:2,w:'sys',kind:'Smb-hire',who:'Avery R.',t:'11:57 PM'},
   {s:2,w:'agent',n:'Agent',t:'11:58 PM',b:
    '<p>Your signature is in. Sent to Avery to countersign.</p>'},
   {s:2,w:'agent',n:'Agent',t:'12:01 AM',cont:1,b:
    '<p>Avery countersigned. Adding her to the room.</p>'},
   {s:2,w:'sys',kind:'join',who:'Avery R.',t:'12:01 AM'},
   {s:3,w:'atty',n:'Avery R.',tag:'Attorney',t:'12:26 AM',b:
    '<p>Read it. You don&rsquo;t need to redline the whole thing.</p>'},
   {s:3,w:'atty',n:'Avery R.',t:'12:26 AM',cont:1,b:
    '<p>Clause 8 is the only one that will hurt you.</p>'
    +'<div class="Smb-mcl"><div class="Smb-mclh"><b>Clause 8</b><s>Termination</s></div>'
    +'<div class="Smb-mclr">They can exit<b>15 days notice</b></div>'
    +'<div class="Smb-mclr">You are locked in<b>12 months</b></div></div>'},
   {s:3,w:'you',n:'You',t:'12:27 AM',b:'<p>so I don&rsquo;t need the full review?</p>'},
   {s:3,w:'atty',n:'Avery R.',tag:'Attorney',t:'12:28 AM',b:
    '<p>No. I&rsquo;d just be taking your money.</p>'
    +'<span class="Smb-mrx">&#128184; 1</span><span class="Smb-mrx">&#128526; 1</span>'},
   {s:3,w:'agent',n:'Agent',t:'Thu 4:02 PM',b:
    '<p>Clause 8 redlined and sent. Signed copy filed here.</p>'
    +'<div class="Smb-mlog"><div class="Smb-mlrow"><i class="ph ph-book-open-text"></i>'
    +'<b>First read and issue list<em>Thu</em></b><s>0.75 hr</s></div>'
    +'<div class="Smb-mlrow"><i class="ph ph-pencil-simple-line"></i>'
    +'<b>Redlined clause 8, sent to counsel<em>Thu</em></b><s>1.5 hr</s></div>'
    +'<div class="Smb-mltot">2 entries this week<b>2.25 hr</b><s>$675</s></div></div>'},
   {s:3,w:'sys',kind:'Smb-close',who:'Avery R.',hr:'2.25 hr',fee:'$675'}
  ];

  /* one sentence, four live words, in the order the story happens */
  rail.innerHTML='<p class="Smb-mline">'
   +'<span class="Smb-mst"><i>01</i>You describe it.</span>'
   +'<span class="Smb-mst"><i>02</i>We find your lawyer.</span>'
   +'<span class="Smb-mst"><i>03</i>You approve them.</span>'
   +'<span class="Smb-mst"><i>04</i>The work happens here.</span></p>';
  var steps=[].slice.call(rail.querySelectorAll('.Smb-mst'));

  var CLS={you:'Smb-u1',agent:'Smb-u2',atty:'Smb-u3'};
  tin.innerHTML=T.map(function(m){
    if(m.w==='sys'){
      var h='<div class="Smb-msys '+m.kind+'" data-s="'+m.s+'" data-w="sys">';
      if(m.kind==='Smb-hire') return h
        +'<span class="Smb-mevi Smb-face">'+ini(m.who)+shot(m.who)+'</span>'
        +'<span class="Smb-mevt">You hired <b>'+m.who+'</b></span>'
        +'<span class="Smb-mevx">'+m.t+'</span></div>';
      if(m.kind==='join') return h
        +'<span class="Smb-mevi Smb-face">'+ini(m.who)+shot(m.who)+'</span>'
        +'<span class="Smb-mevt"><b>'+m.who+'</b> joined the room</span>'
        +'<span class="Smb-mevx">'+m.t+'</span></div>';
      return h+'<span class="Smb-mevi Smb-face">'+ini(m.who)+shot(m.who)+'</span>'
        +'<span class="Smb-mevt">Matter closed</span>'
        +'<span class="Smb-mevx">'+m.hr+' &middot; '+m.fee+'</span></div>';
    }
    var face = m.w==='you' ? '&#129327;' : (m.w==='agent' ? '' : ini(m.n));
    return '<div class="Smb-mmsg '+CLS[m.w]+(m.cont?' Smb-cont':'')+'" data-s="'+m.s+'"'
     +' data-w="'+m.w+'" data-av="'+(m.w==='atty'?ini(m.n):'')+'">'
     +'<span class="Smb-mav">'+face+(m.w==='atty'?shot(m.n):'')+'</span>'
     +'<div class="Smb-mbody"><div class="Smb-mhd"><b>'+m.n+'</b>'
     +(m.tag?'<u>'+m.tag+'</u>':'')+'<s>'+m.t+'</s></div>'+m.b+'</div></div>';
  }).join('');
  var msgs=[].slice.call(tin.children);

  var typer=document.createElement('div');
  var TM=[];
  function at(ms,fn){ TM.push(setTimeout(fn,ms)); }
  var cph=document.getElementById('Smb-mcph'), ctx=document.getElementById('Smb-mctx'),
      cgo=document.getElementById('Smb-mcgo');
  function halt(){
    TM.forEach(clearTimeout); TM=[];
    if(ctx){ ctx.textContent=''; }
    if(cph){ cph.classList.remove('Smb-off'); }
    if(cgo){ cgo.classList.remove('Smb-press'); }
    if(typer.parentNode) typer.parentNode.removeChild(typer);
    [].slice.call(tin.querySelectorAll('.Smb-mpick')).forEach(function(p){
      p.parentNode.removeChild(p); });
  }
  function park(el){
    var need=el.offsetTop+el.offsetHeight+22-thr.clientHeight;
    tin.style.transform='translateY('+(need>0?-Math.round(need):0)+'px)';
  }
  function lit(k){
    for(var i=0;i<msgs.length;i++){
      if(i<=k) msgs[i].classList.add('Smb-on'); else msgs[i].classList.remove('Smb-on');
    }
    var st=k<0?0:+msgs[k].getAttribute('data-s');
    for(var j=0;j<steps.length;j++){
      if(j===st) steps[j].classList.add('Smb-on'); else steps[j].classList.remove('Smb-on');
    }
  }
  function land(k, stepped){
    if(stepped){
      msgs[k].classList.add('Smb-drop');
      at(460,function(){ if(msgs[k]) msgs[k].classList.remove('Smb-drop'); });
    }
    lit(k); park(msgs[k]);
    /* chips on anything at or before k are part of the finished state */
    for(var i=0;i<=k;i++){
      if(stepped && i===k && !reduce && msgs[i].querySelector('.Smb-mrx')){ react(k); continue; }
      [].slice.call(msgs[i].querySelectorAll('.Smb-mrx')).forEach(function(c){
        c.classList.add('Smb-pop'); });
    }
  }
  function typeU(k,done){
    var p=msgs[k].querySelector('.Smb-mbody p');
    if(!p){ done(); return; }
    var txt=p.textContent.replace(/\s+/g,' ').trim();
    var ms=Math.max(8,Math.min(16,Math.round(900/Math.max(txt.length,1))));
    cph.classList.add('Smb-off');
    for(var i=1;i<=txt.length;i++)(function(i){
      at(i*ms,function(){ ctx.textContent=txt.slice(0,i); });
    })(i);
    var T=txt.length*ms;
    at(T+170,function(){ cgo.classList.add('Smb-press'); });
    at(T+320,function(){ cgo.classList.remove('Smb-press');
      ctx.textContent=''; cph.classList.remove('Smb-off'); done(); });
  }
  function dots(k,done){
    var w=msgs[k].getAttribute('data-w');
    typer.classList.add('Smb-mtype'); typer.classList.add(CLS[w]);
    typer.innerHTML='<span class="Smb-mav">'+(w==='atty'?msgs[k].getAttribute('data-av'):'')
      +'</span><span class="Smb-mdots"><i></i><i></i><i></i></span>';
    tin.insertBefore(typer,msgs[k]);
    park(typer);
    at(w==='atty'?640:400,function(){
      if(typer.parentNode) typer.parentNode.removeChild(typer);
      typer.classList.remove('Smb-u1'); typer.classList.remove('Smb-u2'); typer.classList.remove('Smb-u3');
      done();
    });
  }
  var FILL=['😅','🙌','👀','❤️','🔥'];
  function react(k){
    var chips=[].slice.call(msgs[k].querySelectorAll('.Smb-mrx'));
    if(!chips.length) return;
    var want=chips.map(function(c){ return c.textContent.trim().split(' ')[0]; });
    var f=FILL.filter(function(e){ return want.indexOf(e)<0; });
    var tray=[f[0],want[0],f[1],want[1],f[2]];
    var bd=msgs[k].querySelector('.Smb-mbody');
    var pick=document.createElement('div');
    pick.classList.add('Smb-mpick');
    pick.innerHTML=tray.map(function(e){ return '<span>'+e+'</span>'; }).join('');
    bd.appendChild(pick);
    var cells=[].slice.call(pick.children);
    at(340,function(){ pick.classList.add('Smb-on'); });
    var t=780;
    want.forEach(function(emo,n){
      var cell=cells[tray.indexOf(emo)];
      at(t,     function(){ cell.classList.add('Smb-hot'); });
      at(t+300, function(){ cell.classList.add('Smb-tap'); });
      at(t+420, function(){ cell.classList.remove('Smb-tap'); cell.classList.remove('Smb-hot');
                            chips[n].classList.add('Smb-pop'); park(msgs[k]); });
      t+=700;
    });
    at(t+320,function(){ pick.classList.remove('Smb-on'); });
    at(t+900,function(){ if(pick.parentNode) pick.parentNode.removeChild(pick); });
  }
  function resetAll(){
    halt();
    msgs.forEach(function(m){
      m.classList.remove('Smb-on'); m.classList.remove('Smb-drop');
      [].slice.call(m.querySelectorAll('.Smb-mrx')).forEach(function(c){ c.classList.remove('Smb-pop'); });
    });
    lit(-1); tin.style.transform='none';
  }
  function railFromThread(){
    var line=thr.scrollTop+thr.clientHeight*0.55, k=0;
    for(var i=0;i<msgs.length;i++) if(msgs[i].offsetTop<=line) k=i;
    if(thr.scrollTop+thr.clientHeight>=thr.scrollHeight-8) k=msgs.length-1;
    var st=+msgs[k].getAttribute('data-s');
    for(var j=0;j<steps.length;j++){
      if(j===st) steps[j].classList.add('Smb-on'); else steps[j].classList.remove('Smb-on');
    }
    /* read once, stays read: everything up to the reading line keeps its ink */
    for(var n=0;n<msgs.length;n++){
      if(n<=k) msgs[n].classList.add('Smb-lit');
      else msgs[n].classList.remove('Smb-lit');
    }
  }
  thr.addEventListener('scroll',function(){ if(mode==='Smb-read') railFromThread(); });

  var mode='auto', cur=-1;
  function setK(k){
    if(k===cur || !msgs.length) return;
    var stepped=(k===cur+1);
    halt();
    cur=k;
    if(k<0){ resetAll(); cur=-1; return; }
    var w=msgs[k].getAttribute('data-w');
    if(!reduce && stepped && k>0 && (w==='agent'||w==='atty')){
      lit(k-1);
      dots(k,function(){ land(k,true); });
      return;
    }
    if(!reduce && stepped && w==='you'){
      if(k>0) lit(k-1);
      typeU(k,function(){ land(k,true); });
      return;
    }
    land(k, stepped);
  }

  /* ---- the player: a timer, once the pin engages ----

     Each step is the same one the scroll driver produced (dots, drop, emoji
     picking), so a skip ahead and a played step look identical. The gaps are
     where Raad's pauses live now: hire, join and close hold longest. */
  var AP=0, started=false, done=false;
  function stop(){ if(AP){ clearTimeout(AP); AP=0; } }
  function gap(k){
    var m=msgs[k];
    if(m.classList.contains('Smb-hire')||m.classList.contains('join')) return 2700;
    if(m.classList.contains('Smb-close')) return 2400;
    var d=1500, w=m.getAttribute('data-w');
    if(w==='agent') d+=400;
    if(w==='atty')  d+=650;
    if(w==='you'){
      var p=m.querySelector('.Smb-mbody p');
      if(p){
        var L=p.textContent.replace(/\s+/g,' ').trim().length;
        d+=Math.max(8,Math.min(16,Math.round(900/Math.max(L,1))))*L+320;
      }
    }
    if(m.querySelector('.Smb-mrx')) d+=1300;   /* the reaction scene needs its time */
    return d;
  }
  function play(){
    stop();
    if(mode!=='auto' || done || !msgs.length) return;
    if(cur>=msgs.length-1){ AP=setTimeout(finish,2200); return; }
    setK(cur+1);
    AP=setTimeout(cur>=msgs.length-1?finish:play, gap(cur));
  }
  function finish(){
    if(done) return;
    done=true; stop();
    /* collapse the rest of the track to right below the reader, so the pin
       lets go here instead of three screens further down */
    var sy=window.pageYOffset||0;
    var top=room.getBoundingClientRect().top+sy;
    var need=Math.max(sy-top+window.innerHeight+90, pin.offsetHeight+40);
    if(need<room.offsetHeight) room.style.minHeight=Math.round(need)+'px';
  }

  var q2=false;
  function measure(){
    q2=false;
    if(mode!=='auto' || !msgs.length) return;
    var top=room.getBoundingClientRect().top;
    if(!started && !reduce && !done && top<=17){
      started=true; AP=setTimeout(play,250);
    }
    if(done) return;
    /* mid-story and unpinned upward: hold the frame; re-pin resumes */
    if(started && !reduce){
      if(top>40){ stop(); }
      else if(!AP && mode==='auto'){ AP=setTimeout(play,300); }
    }
    /* The timer owns the story; scroll no longer fast-forwards it (one wheel
       fling used to jump the whole demo to its end before a single message
       could type). Skipping is what Read is for. Whoever pushes through the
       whole track anyway leaves past the finished room, not a half scene. */
    if(started && top+room.offsetHeight<=window.innerHeight+40){
      stop(); setK(msgs.length-1); done=true;
    }
  }
  function onRoomScroll(){ if(!q2){ q2=true; requestAnimationFrame(measure); } }
  window.addEventListener('scroll',onRoomScroll,{passive:true});
  window.addEventListener('resize',onRoomScroll);

  function apply(){
    halt(); stop();
    var host=document.getElementById('how');
    if(mode==='Smb-read'){
      host.classList.add('Smb-read');
      room.style.minHeight='';
      msgs.forEach(function(m){
        m.classList.add('Smb-on'); m.classList.remove('Smb-drop'); m.classList.remove('Smb-lit');
        [].slice.call(m.querySelectorAll('.Smb-mrx')).forEach(function(c){
          c.classList.add('Smb-pop'); });
      });
      tin.style.transform='none'; thr.scrollTop=0; railFromThread();
      return;
    }
    host.classList.remove('Smb-read');
    msgs.forEach(function(m){ m.classList.remove('Smb-lit'); });
    /* choosing Watch again after the story ended is a replay: the track grows
       back (below the reader, so nothing jumps) and the pin re-engages */
    if(done){ done=false; started=false; room.style.minHeight=''; }
    resetAll(); cur=-1;
    if(reduce){
      lit(msgs.length-1); park(msgs[msgs.length-1]);
      msgs.forEach(function(m){
        [].slice.call(m.querySelectorAll('.Smb-mrx')).forEach(function(c){
          c.classList.add('Smb-pop'); }); });
      return;
    }
    measure();
  }
  [].slice.call(document.querySelectorAll('.Smb .Smb-mvt')).forEach(function(b){
    b.onclick=function(){
      [].slice.call(document.querySelectorAll('.Smb .Smb-mvt')).forEach(function(x){
        x.classList.remove('Smb-on'); });
      b.classList.add('Smb-on');
      mode=b.getAttribute('data-v');
      apply();
      /* the toggle changes the track length under the reader's feet; put the
         window back on the pin line so it never appears to jump */
      var y=(room.getBoundingClientRect().top+(window.pageYOffset||0))-16;
      window.scrollTo(0,Math.max(0,y));
    };
  });
  apply();
})();

/* ---- the window breaks the fold, then settles into the section ----

   At load the heading column is transparent, so the window rides up over it
   and its top bar is what the fold cuts. Scrolling walks it down into place
   while the column fades in; by the time the pin engages the transform is
   gone and the story starts. Translate only, so the text inside stays sharp. */
(function(){
  var room=document.getElementById('Smb-mroom'),
      win=document.querySelector('.Smb .Smb-mwin'),
      col=document.getElementById('Smb-mcol');
  if(!room || !win || !col) return;

  var wide=window.matchMedia('(min-width:901px)');
  var still=window.matchMedia('(prefers-reduced-motion: reduce)');

  function rest(){
    win.style.transform=''; win.style.willChange='';
    col.style.opacity=''; col.style.transform='';
  }

  var q=false, parked=false;
  function frame(){
    q=false;
    if(still.matches){
      if(!parked){ rest(); parked=true; } return;
    }
    var sy=window.pageYOffset||0;
    /* the scroll distance from page top to the moment the pin engages */
    var pinAt=room.getBoundingClientRect().top+sy-16;
    if(pinAt<40){ if(!parked){ rest(); parked=true; } return; }
    var p=sy/pinAt;
    if(p<0) p=0; if(p>1) p=1;
    p=p*p*(3-2*p);                    /* smoothstep, so it eases in and out */

    if(p>=1){ if(!parked){ rest(); parked=true; } return; }
    parked=false;
    var rise=Math.max(0,win.offsetTop-col.offsetTop); /* the column it rides over */
    win.style.willChange='transform';
    win.style.transform='translateY('+(-rise*(1-p)).toFixed(1)+'px)';
    col.style.opacity=p.toFixed(3);
    col.style.transform='translateY('+(14*(1-p)).toFixed(1)+'px)';
  }
  function onScroll(){ if(!q){ q=true; requestAnimationFrame(frame); } }

  window.addEventListener('scroll',onScroll,{passive:true});
  window.addEventListener('resize',onScroll);
  if(wide.addEventListener) wide.addEventListener('change',onScroll);
  frame();
})();

function SmbFaq(b){
  var q=b.parentElement, open=q.classList.contains('Smb-open');
  document.querySelectorAll('.Smb .Smb-qa').forEach(function(x){ x.classList.remove('Smb-open'); });
  if(!open){ q.classList.add('Smb-open'); }
}
